# Generated by Django 4.1.2 on 2022-11-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0004_alter_reservation_event_alter_reservation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='id',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='token',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name='トークン'),
        ),
    ]
