# Generated by Django 4.1.2 on 2022-11-10 04:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0005_remove_reservation_id_alter_reservation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='トークン'),
        ),
    ]
