# Generated by Django 4.1.2 on 2022-10-27 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'イベント', 'verbose_name_plural': 'イベント'},
        ),
    ]
