# Generated by Django 4.1.3 on 2022-11-18 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0003_event_host_event_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='h', to=settings.AUTH_USER_MODEL, verbose_name='主催者'),
        ),
        migrations.AlterField(
            model_name='event',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s', to=settings.AUTH_USER_MODEL, verbose_name='スタッフ'),
        ),
    ]
